### ISSUE TITLE
Pathfinding automatism not working in native games.

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#125]
The example provided with GDevelop doesn't work too (only when previewed in native game).

**Comment by 4ian** [comment]
Indeed that's strange because it used to work. I'm investigating.

**Comment by 4ian** [comment]
Fixed in https://github.com/4ian/GD/commit/ebb5bbde6f77ebbb2b9e789cb841b70b3bed7067 :)

Simple mistake in a comparison function between nodes. This highlight the fact that tests were missing, so I've added a very basic test for the extension. Could be useful next time a refactoring/change is made :)

Thanks for reporting it, as I'm working on Mac these times I can't really test native games properly.
