### ISSUE TITLE
TileMapObject : Crash when tiles are bigger than the texture itself

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#129]
A crash happens when tiles are bigger than the texture itself.

(Assigned to me).

**Comment by 4ian** [comment]
A check should be added :)
By the way I added you as a collaborator so that you can be assigned to issues. You also have write access to the repo but you can continue working on your own fork and send pull requests as usual (just avoid pushing to master in this repo, I prefer to review all things using Pull Requests :))

**Comment by victorlevasseur** [comment]
No problems, thanks.
