### ISSUE TITLE
**Platform** collision mask stay on the scene if reloading the same scene with different external layout

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#136]
See http://forum.compilgames.net/viewtopic.php?p=51038#p51037 for an example project

Happens only in JS.

**Comment by 4ian** [comment]
I'm on it. Due to the fact that automatisms shared data (i.e: platforms for the platformer engine, obstacles for pathfinding...) are stored in a hashtable by referencing the scene name. 
Instead, I'll store them in the runtimeScene. It will be more logical as the scene is indeed owning these shared data. And it will allow these shared data to be destroyed when the scene is destroyed.

In the C++ game engine, this is already fine because shared data are either stored into the scene or, for other uses where an extension keep reference to data for a specific scene, in maps with keys being the scene memory address, which is unique for each scene.

**Comment by 4ian** [comment]
Fixed in https://github.com/4ian/GD/commit/7ed8c2f15ee0bd4786ca9a5e95d395aef907f334 :)
