### ISSUE TITLE
Pathfinding bug : when destination is on the next/previous column/line (from the starting point)

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#196]
In the Pathfinding playground test that you added in the previous commit, the player can't move to the destination if the destination is on next/previous line/column. However, it works if the destination is close to him (1/2/3 cells away).

Here is an example : 
![pathfindingproblem](https://cloud.githubusercontent.com/assets/964512/9664822/88cd93ac-526c-11e5-9cfc-4c6b7081131a.gif)

Note : if I deactivate the maximum loop counter in the pathfinding ~~automatism~~ behavior, GDevelop crash because of an infinite loop

**Comment by 4ian** [comment]
Thanks, your video was greatly helpful: there was an issue that was visible when going from a cell to another which position was 1;4 (relative to the first one) (or -1;4, or 1;-4, etc...).
This was due to the use of std::multiset to store nodes sorted by their cost. When you use `std::multiset::erase` with anything else than an iterator, all node which are equivalent to the node deleted are also deleted. So at the end some nodes were never considered, making either false path or no path at all.
Fix is in https://github.com/4ian/GD/commit/487a4dd8cb6162b2db1a097bc1a2c0a689516ac2 and I've added a unit test for it :)
