### ISSUE TITLE
Gtk critical error: widget set size request failed

### ISSUE THREAD

**Issue by brylie** [4ian/GD#229]
When starting a new project, the following errors appear in my console:

```sh
(GDIDE:1556): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(GDIDE:1556): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed
```

# Environment
Ubuntu 15.10
GDevelop version 4.0.87.0

**Comment by victorlevasseur** [comment]
This is not a bug (just a warning inside GTK because of wxwidgets).

**Comment by brylie** [comment]
Alright, it said it was critical. Also, there are a lot of similar warnings, and the program is nearly inoperable.

**Comment by victorlevasseur** [comment]
I get all those warning on my Linux and GDevelop is fully operable.

**Comment by 4ian** [comment]
Yup, nothing harmful here - these warnings have been here for a long time and seems to be caused by a misuse of GTK by wxWidgets. I've been able to use GDevelop on previous Ubuntu versions without problems even with these warnings. :)
I guess we can safely ignore them - if there is any other bug, there are probably not related to them.

**Comment by 4ian** [comment]
But I agree it's quite disturbing :/

**Comment by cryptopsy0** [comment]
is this related to dropdown menus losing focus?  https://www.youtube.com/shorts/irzF3fEKgSM
