### ISSUE TITLE
Cannot change password on GD wiki

### ISSUE THREAD

**Issue by brylie** [4ian/GD#230]
I have registered on the GD wiki, so that I can update some of the documentation. My username is `brylie`.

Right now, I am unable to do any of the following:
* change my password to one that I will remember

How can I set my password?

**Comment by 4ian** [comment]
For editing a page, use the tool menu:

<img width="374" alt="screen shot 2015-12-28 at 12 14 06" src="https://cloud.githubusercontent.com/assets/1280130/12017889/8955f328-ad5c-11e5-8c0b-57f0535cc9cf.png">

You can click on **`Edit`** buttons that are embed in a page to edit a particular section of the page (useful on long pages, but if you want to modify the whole page, use the tool menu).

To add a new page, simply enter its url (try to be consistent with existing pages), for example: http://wiki.compilgames.net/doku.php/gdevelop/tutorials/myawesometutorial
You can then edit the page to create it. Don't forget to create a link in an existing page to your new page then :wink: See also the [tutorial page](http://wiki.compilgames.net/doku.php/gdevelop/tutorials), there is a small explanation at the bottom.
One final note: the first header of the page is used as the title.

For changing the password, well I'm not sure how mediawiki (the cms I'm using) handle that :/ Also I've disabled profile page because I'm not sure it provide a real value for most users?

**Comment by brylie** [comment]
Ah, the wiki uses the Dokuwiki engine. Normally, in Dokuwiki, there is a user settings page.

**Comment by brylie** [comment]
![screenshot-2_001](https://cloud.githubusercontent.com/assets/17307/12018230/0895fcb2-ad69-11e5-9252-e76e9d46318a.png)

**Comment by brylie** [comment]
What is missing in the GD Dokuwiki is the Update Profile link.

**Comment by brylie** [comment]
Normally, the Dokuwiki User Profile page is accessible at `doku.php?do=profile`. However, when I pass in the `do=profile` parameter, I get the following message:

![screenshot-3_001](https://cloud.githubusercontent.com/assets/17307/12018309/a551f718-ad69-11e5-8c11-dce286c6cdab.png)

It seems like the profile module may be disabled.

**Comment by 4ian** [comment]
Yep that's it, I've disabled it because in my view it would not provide a lot of value - most people just go on the wiki to read the help/tutorials and contribute, but to introduce yourself there are the forums :)

**Comment by brylie** [comment]
OK, well I would like to contribute to the documentation effort. However, I don't want to reset my password via email each time I want to log in. The profile page is the only way I know to change my password.

**Comment by 4ian** [comment]
I probably misunderstood the way the profile page was working - it's activated again :)

**Comment by 4ian** [comment]
I'll close the issue when you confirm that you have been able to change your password.

**Comment by brylie** [comment]
Thanks @4ian :-)
