### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by acterhd** [4ian/GD#268]
Hello. I have question: have you multiplayer support or not?

**Comment by zatsme** [comment]
What kind of multiplayer?  Same screen, yes of course.  Lan, internet, yes as you can use JavaScript events to do this if you have the skill.

**Comment by acterhd** [comment]
I want game like agar.io

**Comment by 4ian** [comment]
For now there is no strong solution built into GD to make large multiplayer game. 
This is a complex field so for now nothing has been built, but maybe in the future! :)

**Comment by HeadClot** [comment]
Hey just thought I would chime in on this.

My advice would be to look at these articles on [phaser quest](http://www.dynetisgames.com/tag/phaser-quest/) It was a small scale MMO made with Phaser and I want to say Node.js

**Comment by 4ian** [comment]
Hey 👋 I've put this issue on the roadmap (so that anyone can vote for it!) there: https://trello.com/c/kopSIDP5/85-add-support-for-real-time-turn-by-turn-multiplayer

I'm closing this issue as open issues on Github is now be dedicated to bugs only :) (But it's still possible to continue the discussion on this issue even if it's closed)

**Comment by arthuro555** [comment]
It is not direct multiplayer and it is not for games like agar io, but there is #1842 that can allow P2P, for example for little lan games.
