### ISSUE TITLE
[Feature Request] Use system SFML and install outside of /opt on linux

### ISSUE THREAD

**Issue by DataDrake** [4ian/GD#272]
I don't really see a reason why you guys pull down and build your own SFML if it is already available asa system library. Further, not being able to override the install prefix is super frustrating. /opt is not an acceptable location for a package install.

I would love to package GDevelop for Solus (solus-project.com), but I can't until I am able to build GDevelop into /usr, while using our own SFML library.

**Comment by 4ian** [comment]
The reason is that GDevelop early adopted SFML2 a few years ago and SFML2 wasn't available as a system package in most linux distro at this time - there was only support for SFML 1.x or even no packages at all. 😉  Also, at some moments, GD relied on a few features that were only available in dev builds and not released into an official version before months.

But I guess that now SFML adoption is more complete, it should be not too complicated to improve the CMakeLists.txt file to remove the hardcoded build of SFML and have the one from the system used instead. Just have to make sure that headers are available during the build and that the SFML libraries are linked at the end for the `IDE`/`GDCpp`/`GDCpp_Runtime` targets.

**Comment by akien-mga** [comment]
I'm interested in this being supported too. I wanted to check if I could package GDevelop for my Linux distro Mageia, but I see that it would require some patching of the buildsystem.

BTW I see that you have two patches against SFML. They both seem relatively non-critical and I guess GDevelop would still work fine against the system SFML, but if those patches address real issues, it would likely be worth trying to get them reviewed upstream.

**Comment by SolarLune** [comment]
Yo! Has anything changed since February regarding this?

**Comment by 4ian** [comment]
It's unlikely that I change this soon, maybe someone could update the build (CMake files and such) to rely on the system provided SFML.
I'm currently working on a brand-new editor that is based on different technologies (JS with Electron, Emscripten, React, Pixi.js) so it's my main focus: http://forum.compilgames.net/viewtopic.php?f=18&t=9122&sid=2b812410fb1b2eb42acdfa0f187a1b56

My main goal is to make this new editor feature complete so that new user can start using it instead of GDevelop 4, and progressively migrate everyone from GD 4 to this new version.
As it's based on Electron, the cross-platform support is near perfect out-of-the-box (and HDPI/Retina screen support too). So SFML update is not on my todo list for now.

**Comment by 4ian** [comment]
Closing this as GDevelop 5 should not have this issue :)
If someone want to improve things for GD4, help is still welcome!
