### ISSUE TITLE
Remove "Hide tabs of ribbon's page"

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#306]
This option need to be removed as if it is activated, the "File" menu and the "About" menu are not usable.

**Comment by victorlevasseur** [comment]
Fixed in d01a80c.

**Comment by 4ian** [comment]
*In 0b9771815b0b6ee7f0f7b0013c6f79d9721aa2a3 ;)

**Comment by Translator5** [comment]
Linux Mint Cinnamon version
As you activate the option you cant enter the settings menu, so cant activate it deactivate it - as long it is not activated you are totally unable do act (except of the first tab).

**Comment by Translator5** [comment]
Enabling this option in linux-version at least, you can't enable it again.
Because you can't see the menu-bar at all - so you cant enter the options/settings window to disable the option.

There is right now jsut one way to disable the option again, using manual edit of the config-file.

Navigate to "/home/user/.config/GDevelop/options.cfg" ant change the 1 = 0.

`Line72 HidePageTabs=0`

We should add a settings link-icon or sth. like this to the tabs or the start-page!
