### ISSUE TITLE
I wanna create Pause function without changing scene.

### ISSUE THREAD

**Issue by AwesomePaper** [4ian/GD#385]
I want to create Pause function without changing scene.
Can I create Pause function only to changing scene?

Or can I overlap two scenes?

**Comment by 4ian** [comment]
It's possible by setting the time scale of the scene to 0 (or at least of the layer containing the game objects, so that animations on other layers can keep playing!).
In this case, you should also avoid running events related to the gameplay (with a variable called "pause" that you set to 1 when the pause is activated for example). When the user press a key or click a button to unpause the game, set the "pause" variable to 0 and time scale back to 1.

It's not an issue so I'm closing this. Next time please use the forum for this kind of questions ;)
