### ISSUE TITLE
Dynamic point names and sound filenames

### ISSUE THREAD

**Issue by Lizard-13** [4ian/GD#409]
Not an issue at all, but what do you think if we add an option to refer to a point trough a dynamic string?
If you modify the "Object.PointX(pointname)" to accept a dynamic string it would be a compatibility breaker. But you could modify the "Object.X(pointname)", which is not soooo used, to add the option. Or add two extra expressions :)

About dynamic sounds, I know the problem is that you can't copy the files to the exported directory if the name is dynamic, so maybe we should wait until a "Resources manager" handle the to-be-exported files. After that you could export every file in the resources manager and play an error sound (optional) if the dynamic filename doesn't exist, eh? I know it goes against your idea of "easy and no resources manager needed for new users" :/

**Comment by 4ian** [comment]
Answering just now, I think having dynamic points could indeed be interesting but for now I've no real plan to integrate this.
For dynamic sounds, this would need to have the resource manager able to handle sounds indeed, so that we know which sounds can be loaded. No real plan for now but this is something I'd like to improve! 😃

**Comment by Lizard-13** [comment]
Just out of curiosity, it's working modifying the parameter type in the lines [SpriteExtension.cpp#X](https://github.com/4ian/GD/blob/8593249bc6e7b530f3f9686f0832a920162824e2/Core/GDCore/Extensions/Builtin/SpriteExtension/SpriteExtension.cpp#L440) and [SpriteExtension.cpp#Y](https://github.com/4ian/GD/blob/8593249bc6e7b530f3f9686f0832a920162824e2/Core/GDCore/Extensions/Builtin/SpriteExtension/SpriteExtension.cpp#L445) from "" to "string", is it so easy or am I doing something unsafe?

**Comment by 4ian** [comment]
Will looking again at this, yes your modification should work :) But we would need to upgrade all games using points actions/conditions/expressions. The reason why points are not using strings for now is for enabling potentially optimization as the name is not dynamic.

**Comment by 4ian** [comment]
Hey 👋 I've put this issue on the roadmap (so that anyone can vote for it!) there: https://trello.com/c/bV50tnoe/82-add-dynamic-point-names-and-sound-filenames

I'm closing this issue as open issues on Github is now be dedicated to bugs only :) (But it's still possible to continue the discussion on this issue even if it's closed)
