### ISSUE TITLE
Physics behaviour hangs the game 

### ISSUE THREAD

**Issue by noz1ng** [4ian/GD#434]
Created the project at version 5 b13 , then updated GDevelop to current 5 b22, and just wanted to add physics to one of my existings objects - but app hangs at scene preview after that. Same if i create a new one and add physics to him. So, i opened project json and manually add string with physic behaviour into the project extensions list. Then restarted GDevelop, load project... and nothing changes, still hangs at preview

P.S Running at Windows 7 SP1 x64, with all latest KBs and runtimes

**Comment by zatsme** [comment]
I started to use v5 last night after waiting for the physics to be added, thanks 4ian!

I had same issue when playing with it.  Looking at the code in browser debug it reported null values in the size of my objects.

I didn't go any further as I needed sleep ☺️

**Comment by 4ian** [comment]
Can you send me (by email: florian.rival@gmail.com) your game folder
(project file + images)?

I can then debug and issue a new beta version :)

**Comment by noz1ng** [comment]
Looks like i digged out, why. Just look at project .json, and scroll down to "layers" section. Compare to physics tutorial, user created projects are deprived of this code:

```
      "behaviorsSharedData": [
        {
          "gravityX": 0,
          "gravityY": 9,
          "name": "Physics",
          "scaleX": 100,
          "scaleY": 100,
          "type": "PhysicsBehavior::PhysicsBehavior"
        }
      ]
```
So, i just copy-pasted this section from physics tutorial, and its worked for me

**Comment by zatsme** [comment]
Yes so scalex and scaley is null and therefore exception....

Last night i created a new project with b22 and it worked fine, so must be old projects causing issue.  When adding physics behaviour it's not creating the section for some reason?

**Comment by noz1ng** [comment]
Nope, it crashing with new as well. Until i manually added these strings in json

**Comment by 4ian** [comment]
This should be fixed in GD 5 beta 23!
You are also able to edit the gravity and internal options of the physics engine (when at least one object on the scene have the Physics behavior):

<img width="375" alt="screenshot 2018-01-27 19 39 22" src="https://user-images.githubusercontent.com/1280130/35475168-cb06a0b6-0399-11e8-8dbd-db6f3f693548.png">

**Comment by zatsme** [comment]
Yes, works as far as I can see :)

But I think the Gravity should default to Y=9 rather than 0 which it does now!

Also, there are some small things which would help the GUI...and I know this needs to go somewhere else?!

There should be a List of last opened projects at startup
The tabs.... ( Start Page / Scene / Events )  should shift right when you open project manager
Project Manager, layers, instances should open below icon bar, so you can always see icon bar
The icons that open windows should be toggles, so a second click closes the window

Zat.

**Comment by 4ian** [comment]
> But I think the Gravity should default to Y=9 rather than 0 which it does now!

Better indeed, I've changed this for next beta!

> Also, there are some small things which would help the GUI...and I know this needs to go somewhere else?!

For now, you can discuss about this in the forum on this thread: http://forum.compilgames.net/viewtopic.php?f=18&p=64849#p64849

I've noted your ideas anyway :) For project manager I'd like to see if I can add a button/preference to have it pinned on the left.

**Comment by noz1ng** [comment]
Cool! But what about to allow input floating values here? For now, if i wish 0.x gravity, i can't do this using GUI

**Comment by 4ian** [comment]
If think you can but the "." is removed directly while you're typing. I'll change this, for now you can try to copy paste a floating point value in it.
