### ISSUE TITLE
Please add to Random() some new features

### ISSUE THREAD

**Issue by noz1ng** [4ian/GD#435]
Such as possibility to set min value, or negtive value, like that:

Random(min, max)
Random(-42, 42)
Or something, please
It gonna be a very sugar

**Comment by c73k** [comment]
When i need to use some Min-Max Values always use Random() like this: "Random(10)-5" where the min is -5 and the max is 5 :)

**Comment by 4ian** [comment]
Hey 👋 I've put this issue on the roadmap (so that anyone can vote for it!) there: https://trello.com/c/qnKQPmvO/81-add-support-for-randommin-max-in-addition-to-randommax

I'm closing this issue as open issues on Github is now be dedicated to bugs only :) (But it's still possible to continue the discussion on this issue even if it's closed)
