### ISSUE TITLE
Implement Quit Game on HTML5

### ISSUE THREAD

**Issue by noz1ng** [4ian/GD#438]
Afaic understand, there is no "out of box" solution at here, as of current b 23. And i've been a little confused last night, when exported Cordova project just freezes, instead of terminating properly. Any workarounds awhile?

**Comment by noz1ng** [comment]
Not such a problem, as it turned out. Just inserted Cordova code right into project js, so touching a button eventually closes my app. Imo, those things needs to be explained and implemented in the newbie-friendly way, as of GDevelop fundamentals

**Comment by 4ian** [comment]
This would need a page dedicated to Cordova/mobile specificities on the wiki. You can start such a page if you wish, just create an account on wiki.compilgames.net/doku.php/gdevelop5/start :) 

Can you close the issue if there is nothing wrong? So that it's clearer for me when looking at the list of issues.

**Comment by noz1ng** [comment]
Sure, i would create such page later, this will be really helpful for others like me!
