### ISSUE TITLE
TileMapObject : Condition to test collision with a tile ID

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#44]
This function will test if an object collides with a tile with a specific tile ID.
For example : test if a player hits a coin tile (without testing all tiles having a coin tile).

http://forum.compilgames.net/viewtopic.php?f=22&t=5713

**Comment by blurymind** [comment]
The tilemap object is non-existent in gdevelop5.
Perhaps we should think about porting it over or coming up with another one?

Mozilla devs have shared a great example
https://developer.mozilla.org/en-US/docs/Games/Techniques/Tilemaps
https://github.com/mozdevs/gamedev-js-tiles

**Comment by 4ian** [comment]
Thanks for the links! We would need an implementation that works at least with Pixi.js and which is efficient for large maps (including rendering and collisions). This is the tricky part :)

I've added a card there: https://trello.com/c/vJacNvXq/65-support-for-tilemaps-objects-gdevelop-5-html5-games

**Comment by blurymind** [comment]
@4ian thank you! :D 

It would be cool if we could add support to use tiled files. There is an implementation of that here
https://github.com/riebel/pixi-tiledmap

Btw I opened a new issue here on this
https://github.com/4ian/GD/issues/503

**Comment by 4ian** [comment]
Hey 👋 I've put this issue on the roadmap (so that anyone can vote for it!) there: https://trello.com/c/vJacNvXq/65-support-for-tilemaps-objects-tilesets-and-tiled-files-gdevelop-5-html5-games

I'm closing this issue as open issues on Github is now be dedicated to bugs only :) (But it's still possible to continue the discussion on this issue even if it's closed)
