### ISSUE TITLE
Check for Updates feature

### ISSUE THREAD

**Issue by HeadClot** [4ian/GD#449]
It would be nice to be able to have the GD5 editor check for updates automatically. :)

**Comment by 4ian** [comment]
In fact, it's already the case! :) 
GDevelop 5 has an auto-updater mechanism since a few versions. I've created a page in the wiki so that it's documented: http://wiki.compilgames.net/doku.php/gdevelop5/interface/updates

I've not tested it on Linux though.
Also maybe the start page could display a message when a newer version is available so that even if automatic update don't work, users are notified that they can download it.

**Comment by 4ian** [comment]
I'm closing the issue as I've released GD5 beta 26 and you should be able to see this automatic update ;)
Let me know if there is any issue with it.

**Comment by BWPanda** [comment]
> I've not tested it on Linux though.

> Let me know if there is any issue with it.

I've been using v5.0.0-beta61 for a month or so, and I only discovered today that there were new versions available by manually checking the GitHub releases page... Automatic updates are turned on the GDevelop, but they don't seem to be working for me. I'm running Linux Mint 19 Cinnamon.

I've now subscribed to updates via https://coderelease.io/ and manually upgraded to v5.0.0-beta64, so I'll let you know when the next release comes out if GDevelop automatically notifies me or not.
