### ISSUE TITLE
HTML5 games showing just black screen

### ISSUE THREAD

**Issue by shadow4004** [4ian/GD#460]
Not long ago I was using GDevelop 4 and created a a game for html5 with it. It works fine in the browser during preview. Then I exported it uploaded it on some hosting site and opened the link but it only showed a black screen. Now I've upgraded to GDevelop 5. I uploaded the example platformer game that comes with the app using the "Web (upload online)" feature but I'm still having the same problem. I've tried it in chrome, firefox and IE and it's all the same.
Here's a preview:
![game](https://user-images.githubusercontent.com/38155386/38456674-983f392a-3aa0-11e8-91a9-0fe5123504fa.png)

**Comment by 4ian** [comment]
I'm closing this as we don't have any more details.
If you have still the issue, please give us a link to the game :)

**Comment by Lizard-13** [comment]
I can confirm this, online web export gives a black screen, also reported in the forum: http://forum.compilgames.net/viewtopic.php?f=19&t=10888
But it seems that exporting works fine from Mac: http://forum.compilgames.net/viewtopic.php?f=19&t=10641#p68890

Look at this, the game sub-folders are missing :open_mouth: :
![blackscreen](https://user-images.githubusercontent.com/9782647/48874241-01dcde80-edd1-11e8-8965-260ce22422b8.png)
That's why a lot of things are undefined...
The game link: 
http://gd-games.s3-website-eu-west-1.amazonaws.com/game-1542844886744

**Comment by brunobautessebastian** [comment]
the same thing happens to me when exporting for web, the screen is black
[link to my game test](http://gd-games.s3-website-eu-west-1.amazonaws.com/game-1563858595838/)

![Sin título](https://user-images.githubusercontent.com/53241751/61755905-027aaa00-ad90-11e9-9a85-42a068737522.png)

**Comment by 4ian** [comment]
Finally really fixed in beta 79 :)

**Comment by lochnesslegends** [comment]
Still happening now (Dec 2021)
