### ISSUE TITLE
Line color on dark UI for actions/conditions drag''ndrop

### ISSUE THREAD

**Issue by KinkGD** [4ian/GD#600]
In last changelog : 
> Add drag'n'drop support for conditions and actions!
> 
>     You can move the selected condition or action (or more, if you select more than one) to another position in the list or event to a list in another event.

I use the Dark UI for GD5, but if i drag'n'drop actions or conditions from one event to another, the visual marker is black line (almost invisible).

So basically, it's not a feature request, just an idea of UI improvement.

**Comment by 4ian** [comment]
I see, it should be fixable by adding a "class name" for it (in `.../EventsTree/ClassNames.js`), using this classname instead of an hardcoded style in `DropIndicator.js` and finally move the styles to `Theme/DarkTheme/EventsSheet.css` or `Theme/DefaultTheme/EventsSheet.css` (so that we can have a different style for dark and light theme).

@Bouh @Wend1go @Lizard-13 or anyone that want to try, this should be relatively easy to fix (~4 files to changes - and you can check how `ClassNames.js` is used elsewhere as inspiration). Let me know if someone want to try :)

**Comment by 4ian** [comment]
Should have been fixed by @Bouh, color was changed and could also be personalized later separately for the light and dark theme :)
