### ISSUE TITLE
GD beta 50 : unable to rezise any sprite if grid is enabled : sprite disappear on resize

### ISSUE THREAD

**Issue by KinkGD** [4ian/GD#605]
A user on the forum reported this : http://forum.compilgames.net/viewtopic.php?f=19&t=10626

I confirm, there is a problem. Show grid + resize sprite make the sprite to disappear.

**Comment by 4ian** [comment]
Indeed, an invalid height is given to the object. I recommend not using the grid while waiting for the fix to be released. It's fixed in 88486449fb85af76d9fa9c7f89a7703b943a42a1 (and this also protect against negative grid value) (also technically this kind of stupid errors (a missing letter) could be found by Flow if the file was flow typed).

Closing as fixed! Thanks for reporting it :)

**Comment by 4ian** [comment]
Should be fixed in beta51 :)
