### ISSUE TITLE
Can't remove tiles of the TileMapObject using right click in pencil mode

### ISSUE THREAD

**Issue by victorlevasseur** [4ian/GD#67]
Can't remove tiles of the TileMapObject using right click in pencil mode.

**Comment by 4ian** [comment]
Fixed in https://github.com/4ian/GD/commit/da872e840866dfa5d1140befdbadd0a58944be8f
I've also fixed a crash when floodfilling a tile using the same tile id (causing an infinite loop) and when using the pencil with the mouse at a position which is at the left or the top of the origin 0;0.

When possible, always try to use ``unsigned int`` to represent coordinates, it ensures that these numbers won't be negative :smiley:  The only tricky point with unsigned int is:

    unsigned int a = 1;
    if (a-1 >= 0) a--;
    //here a == 0 as expected
    if (a-1 >= 0) a--;
    //here a was decreased because when doing a-1 with a ==0, the result was not -1 but the maximum value for unsigned int, so the condition in the if was *true*. And because of it, the -- operator was applied and so now a is equal to the maximum value for unsigned int.
    //Instead, when dealing with unsigned int, you should always do:
    if (a >= 1) a--;
    //if you need to test if you can decrease an unsigned int.

**Comment by victorlevasseur** [comment]
Ok, thanks

2015-01-04 17:11 GMT+01:00 Florian Rival <notifications@github.com>:

> Closed #67 <https://github.com/4ian/GD/issues/67>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/4ian/GD/issues/67#event-213797246>.
>



-- 
Victor LEVASSEUR
victorlevasseur52@gmail.com
